### PR TITLE
Create clang-musl-patchset-1-r1.ebuild

### PR DESCRIPTION
**Pull request by King-Mucus**
Ebuild para baixar o patchset de uma vez.

### CODE REVIEW

**Comment by leonardohn** [comment]
I don't think this is a clean approach. Instead, we would appreciate if the patches were converted into actual ebuilds, so the overlay can provide them as needed. What do you think?

**Comment by King-Mucus** [comment]
Well. That would be pretty simple. We would only need to copy the ebuilds from the Gentoo repository and then add the patches to the corresponding cat-long/appname/files directory, effectively merging clang-musl-overlay with gentoo-patchset.

It would be definitely cleaner, especially for users that create patches on their own. On the other side, it would require more attention and maintenance work on your/our part.

**Comment by leonardohn** [comment]
That is right, but developers are not supposed to modify the user configuration, and /etc/portage/patches is an user configuration directory. So that would never fit as a definitive solution for this problem. Despite mirrored ebuilds being painful to maintain, we can definitely configure our CI for that, so it mirrors and adds new patches automatically, when possible.

**Comment by leonardohn** [comment]
@unhappy-ending I would be happy to talk about Polly, but would you mind if we continue the discussion on a separate issue?

**Pull request closed without merging**
