### PR TITLE
dev-lang/ghc: add 9.0.2-r1

### PR DESCRIPTION
**Pull request by uidops**
I recently worked on the ghc package for **musl + llvm/clang** profile and finally I managed to port it.
It's a fork of https://github.com/gentoo-haskell/gentoo-haskell/blob/master/dev-lang/ghc/ghc-9.0.2-r1.ebuild.
and I maintain the ghc-bin at https://github.com/uidops/ghc-musl, It can also be maintained under a repository in the clang-musl-overlay organization or something else.

### CODE REVIEW

**Comment by leonardohn** [comment]
Nice! Can you describe the process on how you did it? So I can reproduce it during our automated stage3 bootstrap process, just like we currently do with Rust.

**Comment by uidops** [comment]
> Nice! Can you describe the process on how you did it? So I can reproduce it during our automated stage3 bootstrap process, just like we currently do with Rust.

All that is needed is to change [CC](https://github.com/uidops/clang-musl-overlay/blob/ghc/dev-lang/ghc/ghc-9.0.2-r1.ebuild#L671), [LD](https://github.com/uidops/clang-musl-overlay/blob/ghc/dev-lang/ghc/ghc-9.0.2-r1.ebuild#L695), HOST, TARGET, BUILD and [LLVM target](https://github.com/uidops/clang-musl-overlay/blob/ghc/dev-lang/ghc/ghc-9.0.2-r1.ebuild#L591) and [CFLAGS/CXXFLAGS](https://github.com/uidops/clang-musl-overlay/blob/ghc/dev-lang/ghc/ghc-9.0.2-r1.ebuild#L593) (for disabling "unused command line argument" warning).
I used [redneb's ghc binary package](https://github.com/redneb/ghc-alt-libc/) to build the ghc-bin, then I compiled the [source code of ghc](https://downloads.haskell.org/~ghc/9.0.2/ghc-9.0.2-src.tar.xz).
I fixed LlvmTarget and CFLAGS, then configured the source code with these arguments:
`--target=x86_64-gentoo-linux-musl --host=x86_64-gentoo-linux-musl --build=x86_64-gentoo-linux-musl CC=clang CXX=clang++ LD=ld.lld`
and then `make && make install` and created a binary package from it. after that, I fixed those things in the ebuild and it's working.

**Comment by capezotte** [comment]
The `CC` value in the ebuild is broken for people using our profile, as it's set to `${CHOST}-clang` instead of just `clang`. Should this be fixed by changing our profile or by changing the ebuild?

Also, it installs some additional libraries Gentoo provides as `dev-haskell/*` packages (such as `mtl` and `transformers`). I can't compile `shellcheck` due to `Ebuild author forgot an entry in CABAL_CORE_LIB_GHC_PV (...)` errors in theses dependencies unless I add them to package.provided.

**Comment by uidops** [comment]
> The `CC` value in the ebuild is broken for people using our profile, as it's set to `${CHOST}-clang` instead of just `clang`. Should this be fixed by changing our profile or by changing the ebuild?
> 
> Also, it installs some additional libraries Gentoo provides as `dev-haskell/*` packages (such as `mtl` and `transformers`). I can't compile `shellcheck` due to `Ebuild author forgot an entry in CABAL_CORE_LIB_GHC_PV (...)` errors in theses dependencies unless I add them to package.provided.

Thanks. I'll fix it and send a new merge request

**Pull request merged**
